import { Breadcrumbs } from '../components/Breadcrumbs';
import { SEOHelmet } from '../components/SEOHelmet';
import { Link } from '../context/RouterContext';
import { SITE_CONFIG } from '../data/siteConfig';

export function TermsView() {
  const contactEmail = SITE_CONFIG.contactEmail;

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <SEOHelmet
        title="Terms of Service – Online Tools"
        description="Review the terms governing access and use of Online Tools calculators, converters, and browser utilities."
        canonicalPath="/terms"
      />

      {/* 1. Breadcrumb: Home → Terms of Service */}
      <Breadcrumbs items={[{ label: 'Terms of Service', path: '/terms' }]} />

      {/* 2. Header */}
      <header className="border-b border-[#E4E8EF] pb-6">
        <h1 className="text-2xl sm:text-3xl font-heading font-extrabold text-[#131A2B] tracking-tight">
          Terms of Service
        </h1>
        <div className="mt-2 text-xs sm:text-sm font-sans text-[#5B6577] flex flex-wrap items-center gap-x-4 gap-y-1">
          <span>Effective Date: {SITE_CONFIG.termsEffectiveDate}</span>
          <span className="hidden sm:inline" aria-hidden="true">•</span>
          <span>Last Updated: {SITE_CONFIG.termsLastUpdated}</span>
        </div>
      </header>

      {/* Content Container */}
      <div className="bg-[#FFFFFF] border border-[#E4E8EF] rounded-2xl p-6 sm:p-8 space-y-8 text-sm sm:text-base text-[#5B6577] leading-relaxed shadow-2xs font-sans">
        {/* 3. Acceptance of Terms */}
        <section aria-labelledby="acceptance-heading" className="space-y-3">
          <h2 id="acceptance-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using Online Tools (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;the platform&rdquo;), you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not access or use the website and its utilities.
          </p>
        </section>

        {/* 4. Use of the Website */}
        <section aria-labelledby="use-website-heading" className="space-y-3">
          <h2 id="use-website-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            2. Use of the Website
          </h2>
          <p>
            Online Tools provides online calculators, unit converters, text manipulation utilities, and informational reference guides for general personal, educational, and professional utility. You may access and use these tools in accordance with these terms and all applicable laws and regulations.
          </p>
        </section>

        {/* 5. Tool Results & Calculation Disclaimer */}
        <section aria-labelledby="tool-disclaimer-heading" className="space-y-3">
          <h2 id="tool-disclaimer-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            3. Tool Results and Calculation Disclaimer
          </h2>
          <p>
            All calculators, converters, formulas, and informational guides on this website are provided for general informational, educational, and utility purposes only. While we endeavor to ensure mathematical consistency and implement established formulas, calculation variances, rounding differences, or errors may occur.
          </p>
          <p className="font-heading font-semibold text-[#131A2B]">
            Users should independently verify results when used for important decisions.
          </p>
          <p>
            The outputs generated by our tools do not constitute and should not be relied upon as professional:
          </p>
          <ul className="list-disc list-inside space-y-1 pl-2 text-sm text-[#5B6577]">
            <li>Financial or investment advice</li>
            <li>Medical, health, or dietary advice</li>
            <li>Legal or statutory counsel</li>
            <li>Engineering, structural, or safety specifications</li>
          </ul>
          <p className="text-xs sm:text-sm text-[#5B6577]">
            For high-stakes or critical decisions, consult a qualified professional in the appropriate field.
          </p>
        </section>

        {/* 6. Permitted and Prohibited Use */}
        <section aria-labelledby="prohibited-use-heading" className="space-y-3">
          <h2 id="prohibited-use-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            4. Permitted and Prohibited Use
          </h2>
          <p>
            You agree to use the platform in a respectful and lawful manner. Prohibited activities include, but are not limited to:
          </p>
          <ul className="list-disc list-inside space-y-1.5 pl-2 text-sm text-[#5B6577]">
            <li>Using the website for any unlawful purpose or in violation of any applicable local, national, or international law.</li>
            <li>Attempting to bypass, disable, or circumvent security features, rate limits, or access controls.</li>
            <li>Introducing viruses, trojans, worms, logic bombs, or other malicious or technologically harmful material.</li>
            <li>Launching denial-of-service (DoS/DDoS) attacks or otherwise intentionally interfering with service availability or infrastructure performance.</li>
            <li>Sending abusive automated requests or engaging in aggressive automated scraping that burdens server resources or disrupts service for other users.</li>
            <li>Attempting unauthorized access to server infrastructure, restricted administrative endpoints, or private configurations.</li>
          </ul>
        </section>

        {/* 7. Intellectual Property */}
        <section aria-labelledby="intellectual-property-heading" className="space-y-3">
          <h2 id="intellectual-property-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            5. Intellectual Property
          </h2>
          <p>
            The website design, visual branding, logo, original written text, custom interface components, graphics, code, and other platform materials are the property of Online Tools or its licensors and are protected by applicable copyright, trademark, and intellectual property laws.
          </p>
          <p>
            We do not claim ownership over the texts, numbers, data, or inputs you enter into our calculators and utilities. You retain full ownership and responsibility for the content and information you submit or process using the platform.
          </p>
        </section>

        {/* 8. Third-Party Services */}
        <section aria-labelledby="third-party-heading" className="space-y-3">
          <h2 id="third-party-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            6. Third-Party Services
          </h2>
          <p>
            Some tools, features, or infrastructure components on this platform may rely on third-party services, such as hosting infrastructure, content delivery networks, web font providers, or external reference APIs. We do not operate or control third-party services and are not responsible for their availability, policies, or practices.
          </p>
        </section>

        {/* 9. Availability and Changes */}
        <section aria-labelledby="availability-heading" className="space-y-3">
          <h2 id="availability-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            7. Availability and Changes
          </h2>
          <p>
            We continuously work to maintain and improve the platform. However, we do not guarantee that the website or any individual tool will be available uninterrupted, error-free, or perpetually accessible. We reserve the right to modify, update, temporarily suspend, or discontinue any tool, feature, or content at any time without prior notice.
          </p>
        </section>

        {/* 10. Disclaimer of Warranties */}
        <section aria-labelledby="warranties-heading" className="space-y-3">
          <h2 id="warranties-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            8. Disclaimer of Warranties
          </h2>
          <p>
            The website, calculators, converters, and all associated content are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, without warranties of any kind, whether express, implied, statutory, or otherwise. To the extent permissible by law, we disclaim any implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, or continuous availability.
          </p>
        </section>

        {/* 11. Limitation of Liability */}
        <section aria-labelledby="liability-heading" className="space-y-3">
          <h2 id="liability-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            9. Limitation of Liability
          </h2>
          <p>
            To the extent permitted by applicable law, Online Tools and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, or business opportunities, arising out of or in connection with your access to, use of, or inability to use the website, tools, or calculation outputs.
          </p>
        </section>

        {/* 12. Changes to Terms */}
        <section aria-labelledby="changes-heading" className="space-y-3">
          <h2 id="changes-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            10. Changes to Terms
          </h2>
          <p>
            We may update these Terms of Service periodically to reflect operational, legal, or feature updates. When changes are made, the revised terms will be posted on this page with an updated &ldquo;Last Updated&rdquo; date. Your continued use of the website following any modifications signifies your acceptance of the updated terms.
          </p>
        </section>

        {/* 13. Contact */}
        <section aria-labelledby="terms-contact-heading" className="space-y-3 border-t border-[#E4E8EF] pt-6">
          <h2 id="terms-contact-heading" className="text-lg font-heading font-bold text-[#131A2B]">
            11. Contact Us
          </h2>
          {contactEmail ? (
            <p>
              If you have any questions or concerns regarding these Terms of Service, please contact us by email at{' '}
              <a
                href={`mailto:${contactEmail}`}
                className="text-[#2563EB] font-heading font-semibold underline hover:text-[#1D4ED8]"
              >
                {contactEmail}
              </a>{' '}
              or via our{' '}
              <Link href="/contact" className="text-[#2563EB] font-heading font-semibold underline hover:text-[#1D4ED8]">
                Contact page
              </Link>.
            </p>
          ) : (
            <p>
              If you have any questions or concerns regarding these Terms of Service, please reach out via our{' '}
              <Link href="/contact" className="text-[#2563EB] font-heading font-semibold underline hover:text-[#1D4ED8]">
                Contact page
              </Link>.
            </p>
          )}
        </section>
      </div>
    </div>
  );
}
